{% extends "template/Dockerfile.global.sh.twig" %}

{% block shopware %}
{% endblock %}

{% block ssl %}
{% endblock %}

{% block components_xdebug %}
    RUN cd /var/www \
    && apt-get update \
{% for key, value in php.versions %}
{% if value.xdebug_version != '' %}
{% if value.active==1 %}
{% include 'template/components/xdebug/install.sh.twig' with { "php_version" : key,"folder_id" : value.folder_id, "xdebug_tag":value.xdebug_tag} %}
{% endif %}
{% endif %}
{% endfor %}
&& sudo apt-get install -y zlib1g-dev \
&& sudo rm -rf /var/lib/apt/lists/* /var/cache/apt/* \
&& sudo rm -rf /var/www/xdebug

#generate xdebug ini files
{% for key, value in php.versions %}
{% if value.xdebug_version != '' %}
{% if value.active==1 %}
{% include 'template/components/xdebug/generate_ini_files.sh.twig' with { "version" : key, "folder_id" : value.folder_id ,"xdebug_version":value.xdebug_version} %}
{% endif %}
{% endif %}
{% endfor %}

RUN cd /var/www \
{% for key, value in php.versions %}
{% if value.xdebug_version != '' %}
{% if value.active==1 %}
{% include 'template/components/xdebug/edit_ini_files.sh.twig' with { "version" : key, "folder_id" : value.folder_id ,"xdebug_version":value.xdebug_version} %}
{% endif %}
{% endif %}
{% endfor %}
 && cd /var/www
{% endblock %}


{% block components %}

{{ parent() }}

{% block components_nvm %}

    sudo su www-data
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    nvm i 16
    nvm use 16
    nvm alias default node

    echo 'export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"' >> /var/www/.bashrc
    echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm' >> /var/www/.bashrc
    echo '16' >> /var/www/.nvmrc
    exit

{% endblock %}
{% endblock %}


{% block php %}

    {{ parent() }}

    {% for key,value in php.versions %}
        {% if value.active == true %}
         sed -i "s~sendmail_path = /usr/sbin/ssmtp~sendmail_path = /usr/sbin/sendmail -S mail:1025~" /etc/php/{{ key }}/fpm/conf.d/01-general.ini
        {% endif %}
    {% endfor %}

{% endblock %}