{% extends "template/Dockerfile.global.sh.twig" %}

{% block shopware %}
{% endblock %}

{% block ssl %}
{% endblock %}

{% block components_xdebug %}
    RUN cd /var/www \
    && apt-get update \
{% for key, value in php.versions %}
{% if value.xdebug_version != '' %}
{% if value.active==1 %}
{% include 'template/components/xdebug/install.sh.twig' with { "php_version" : key,"folder_id" : value.folder_id, "xdebug_tag":value.xdebug_tag} %}
{% endif %}
{% endif %}
{% endfor %}
&& sudo apt-get install -y zlib1g-dev \
&& sudo rm -rf /var/lib/apt/lists/* /var/cache/apt/* \
&& sudo rm -rf /var/www/xdebug

#generate xdebug ini files
{% for key, value in php.versions %}
{% if value.xdebug_version != '' %}
{% if value.active==1 %}
{% include 'template/components/xdebug/generate_ini_files.sh.twig' with { "version" : key, "folder_id" : value.folder_id ,"xdebug_version":value.xdebug_version} %}
{% endif %}
{% endif %}
{% endfor %}

RUN cd /var/www \
{% for key, value in php.versions %}
{% if value.xdebug_version != '' %}
{% if value.active==1 %}
{% include 'template/components/xdebug/edit_ini_files.sh.twig' with { "version" : key, "folder_id" : value.folder_id ,"xdebug_version":value.xdebug_version} %}
{% endif %}
{% endif %}
{% endfor %}
 && cd /var/www
{% endblock %}